config/routes.rb
Rails.application.routes.draw do

  get 'static/index'
  root 'static#index'

  get '/about'       => 'static#about'
  get '/portfolio'     => 'static#portfolio'
  get '/services'       => 'static#services'
  get '/privacy-policy'     => 'static#privacy-policy'
  get '/terms'     => 'static#terms'
  get '/faqs' => 'static#faqs'
  get '/links' => 'static#links'

  get '/portfolio/firmatek' => 'static#portfolio_firmatek'
  get '/portfolio/outwellness-atx' => 'static#portfolio_outwellnessatx'
  get '/portfolio/nonprofit-website' => 'static#portfolio_nonprofit_website', as: 'portfolio_foundation_website'
  get '/portfolio/community-impact-website' => 'static#portfolio_community_impact_website'
  get '/portfolio/youth-career-resource-website' => 'static#portfolio_youthcareer', as: 'portfolio_youthcareer'
  get '/portfolio/capitalize' => 'static#portfolio_capitalize'
  get '/portfolio/mfour' => 'static#portfolio_mfour'
  get '/portfolio/compost-products-website' => 'static#portfolio_greenerworld', as: 'portfolio_greenerworld'
  get '/portfolio/electrical-industry-website' => 'static#portfolio_electricalalliance', as: 'portfolio_electricalalliance'
  get '/portfolio/genie-creates' => 'static#portfolio_genie', as: 'portfolio_genie'
  get '/portfolio/north-bloom' => 'static#portfolio_northbloom', as: 'portfolio_northbloom'
  get '/portfolio/betty-boujee' => 'static#portfolio_bettyboujee', as: 'portfolio_bettyboujee'
  get '/portfolio/agency-website' => 'static#portfolio_agency', as: 'portfolio_agency'
  get '/portfolio/community-retail-showcase' => 'static#portfolio_community', as: 'portfolio_community'
  get '/portfolio/igco' => 'static#portfolio_igco'
  get '/portfolio/expertly-sanitized' => 'static#portfolio_expertlysanitized', as: 'portfolio_expertly'
  get '/portfolio/universal-control-systems' => 'static#portfolio_ucs', as: 'portfolio_ucs'
  get '/portfolio/marysol-wellness' => 'static#portfolio_marysol', as: 'portfolio_marysol'
  get '/portfolio/zack-pride' => 'static#portfolio_zackpride', as: 'portfolio_zackpride'
  get '/portfolio/leeward-team' => 'static#portfolio_leewardteam', as: 'portfolio_leewardteam'
  get '/portfolio/the-picnic-hour' => 'static#portfolio_picnichour', as: 'portfolio_picnichour'
  get '/portfolio/not-your-average-picnic' => 'static#portfolio_nyap', as: 'portfolio_nyap'
  get '/portfolio/picnics-in-the-city' => 'static#portfolio_picnics', as: 'portfolio_picnics'
  get '/portfolio/reliant-home-security' => 'static#portfolio_reliantsecurity', as: 'portfolio_reliantsecurity'
  get '/portfolio/reliant-mass-campaign' => 'static#portfolio_reliantmass', as: 'portfolio_reliantmass'
  get '/portfolio/joshespin' => 'static#portfolio_joshespin'
  get '/portfolio/jumpix' => 'static#portfolio_jumpix'
  get '/portfolio/ibuildamerica' => 'static#portfolio_iba', as: 'portfolio_iba'
  get '/portfolio/cia' => 'static#portfolio_cia'
  get '/portfolio/turner-mining-group' => 'static#portfolio_tmg', as: 'portfolio_tmg'
  get '/portfolio/captivecolour' => 'static#portfolio_captivecolour'
  get '/portfolio/snapple-video' => 'static#portfolio_snapple', as: 'portfolio_snapple'
  get '/portfolio/jarrod-lee' => 'static#portfolio_jarrodlee', as: 'portfolio_jarrodlee'

  get '/portfolio/apg' => 'static#portfolio_apg'
  get '/portfolio/hcss' => 'static#portfolio_hcss'
  get '/portfolio/artofgreenwood' => 'static#portfolio_greenwood'
  get '/portfolio/neydi-photography' => 'static#portfolio_neydiphotography', as: 'portfolio_neydi'
  get '/portfolio/manifesting-money-studio' => 'static#portfolio_mms', as: 'portfolio_mms'
  get '/portfolio/cameron-lee' => 'static#portfolio_csl', as: 'portfolio_csl'

  resources :contacts, only: :create
  match '/contact', to: 'contacts#new', via: 'get'

end

app/views/shared/_footer.html.slim
#footer
	.footer-wrapper
		.container
			.row
				.col-md-4.col-sm-12
					h4 About
					p Vanessa Amilet blends UX, design, and development to create digital experiences that are intuitive, impactful, and authentically aligned with your brand.
					p
						= link_to "Learn More »", about_path
				.col-md-2.col-sm-2
					.fu-logo
						= link_to "https://www.freelancersunion.org?utm_source=badge&utm_campaign=member&utm_content=member-stamp-200", target:"_blank"  do
							= image_tag "https://assets.freelancersunion.org/static/images/member-badge.ec82f86413ea.svg", alt: 'Proud member of Freelancers Union', :height=>"100", :width=>"100"
				.col-md-3.col-sm-6
					h4 Menu
					nav.footer-nav
						ul
							li
								= link_to "Schedule a Consultation", "https://calendly.com/vanessa-amilet"
							li
								= link_to "Projects", portfolio_path
							li
								= link_to "Services", services_path
							li
								= link_to "Contact", contact_path
							li
								= link_to "FAQs", faqs_path

				.col-md-3.col-sm-6
					h4 Connect
					ul.social
						li.linkedin
							= link_to "https://www.linkedin.com/in/vanessaamilet", target:"_blank" do 
								i.fa-brands.fa-linkedin-in
						li.github
							= link_to "https://github.com/vanessaamilet", target:"_blank" do
								i.fa-brands.fa-github
						li.dribbble
							= link_to "https://dribbble.com/vanessaamilet", target:"_blank" do
								i.fa-brands.fa-dribbble
						/ li.instagram
						/ 	= link_to "https://www.instagram.com/vanessaamilet/", target:"_blank" do
						/ 		i.fa-brands.fa-instagram

	.sub-footer.d-flex.align-items-center
		.container
			.row
				.col-lg-4
					p.credit.text-left
						| &copy;&nbsp;
						= Time.zone.now.year
						= link_to " Vanessa Amilet", root_path
				.col-lg-4
					p.credit.text-lg-center
						| Made with <i class="fa fa-heart"></i> in ATL.
				.col-lg-4
					p.credit.text-lg-right
						= link_to "Privacy Policy", privacy_policy_path
						|  • 
						= link_to "Terms of Service", terms_path

app/views/shared/_google_analytics.html.slim
<!-- Global site tag (gtag.js) - Google Analytics -->
- if Rails.env == "production"
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-42793330-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'UA-42793330-1');
	</script>

app/views/shared/_portfolio_browsemore.html.slim
section.portfolio-grid.browse-more
    .container
        .row.justify-content-between.align-items-center
            .col-lg-5
                h3 Browse More Projects
            .col-lg-7.text-lg-end
                = link_to 'View All Projects <i class="fad fa-arrow-alt-circle-right"></i>'.html_safe, portfolio_path, class:'view-projects'
        / .row.projects
		/ 	.col-md-4
		/ 		.col-md-4
		/ 		= link_to portfolio_picnics_path, class: 'portfolio-card card' do
		/ 		 	= image_tag "portfolio/portfolio-picnicsinthecity.jpg", :class=>"card-img", :alt=>"Picnics in the City"
		/ 			.card-body
		/ 				h5.card-title Picnics in the City
		/ 				p.card-text Custom Shopify Website
		/ 				p View Project »
		/ 	.col-md-4
		/ 		= link_to portfolio_marysol_path, class: 'portfolio-card card' do
		/ 		 	= image_tag "portfolio/portfolio-marysol.jpg", :class=>"card-img", :alt=>"Mar y Sol Therapy & Wellness"
		/ 			.card-body
		/ 				h5.card-title Mar y Sol Therapy & Wellness
		/ 				p.card-text Wordpress Website
		/ 				p View Project »
		/ 	.col-md-4
		/ 		= link_to portfolio_zackpride_path, class: 'portfolio-card card' do
		/ 		 	= image_tag "portfolio/portfolio-zackpride.jpg", :class=>"card-img", :alt=>"Zack Pride"
		/ 			.card-body
		/ 				h5.card-title Zack Pride
		/ 				p.card-text Custom Wordpress Website
		/ 				p View Project »
		/ .row.projects
		/ 	.col-md-4
		/ 		= link_to portfolio_expertly_path, class: 'portfolio-card card' do
		/ 		 	= image_tag "portfolio/portfolio-expertlysanitized.jpg", :class=>"card-img", :alt=>"Expertly Sanitized"
		/ 			.card-body
		/ 				h5.card-title Expertly Sanitized
		/ 				p.card-text Custom Wordpress Website
		/ 				p View Project »
		/ 	.col-md-4
		/ 		= link_to portfolio_bettyboujee_path, class: 'portfolio-card card' do
		/ 		 	= image_tag "portfolio/portfolio-bettyboujee.jpg", :class=>"card-img", :alt=>"Betty Boujee"
		/ 			.card-body
		/ 				h5.card-title Betty Boujee
		/ 				p.card-text Custom Shopify Website
		/ 				p View Project »
		/ 	.col-md-4
		/ 		= link_to portfolio_igco_path, class: 'portfolio-card card' do
		/ 		 	= image_tag "portfolio/portfolio-igco.jpg", :class=>"card-img", :alt=>"IGCO"
		/ 			.card-body
		/ 				h5.card-title IGCO
		/ 				p.card-text Custom Wordpress Website
		/ 				p View Project »
		/ .row.projects
		/ 	.col-md-4
		/ 		= link_to portfolio_jarrodlee_path, class: 'portfolio-card card' do
		/ 		 	= image_tag "portfolio/portfolio-jarrodlee.jpg", :class=>"card-img", :alt=>"Jarrod Lee"
		/ 			.card-body
		/ 				h5.card-title Jarrod Lee
		/ 				p.card-text Custom Wordpress Website
		/ 				p View Project »
		/ 	.col-md-4
		/ 		= link_to portfolio_captivecolour_path, class: 'portfolio-card card' do
		/ 		 	= image_tag "portfolio/portfolio-captivecolour.jpg", :class=>"card-img", :alt=>"CaptiveColour Cosmetics"
		/ 			.card-body
		/ 				h5.card-title CaptiveColour
		/ 				p.card-text Branding, Custom Shopify Website
		/ 				p View Project »
		/ 	.col-md-4
		/ 		= link_to portfolio_ucs_path, class: 'portfolio-card card' do
		/ 		 	= image_tag "portfolio/portfolio-ucs.jpg", :class=>"card-img", :alt=>"Universal Control Systems"
		/ 			.card-body
		/ 				h5.card-title Universal Control Systems
		/ 				p.card-text Custom Wordpress Website
		/ 				p View Project »
        / .row.projects
        /     .col-md-4
		/ 		= link_to portfolio_iba_path, class: 'portfolio-card card' do
		/ 		  = image_tag "portfolio/portfolio-iba.jpg", :class=>"card-img", :alt=>"I Build America"
		/ 		  .card-body
		/ 			h5.card-title I Build America
		/ 			p.card-text Custom Wordpress Website
		/ 			p View Project »
		/ 	.col-md-4
		/ 		= link_to portfolio_jumpix_path, class: 'portfolio-card card' do
		/ 		  = image_tag "portfolio/portfolio-jumpix.jpg", :class=>"card-img", :alt=>"Jumpix"
		/ 		  .card-body
		/ 			h5.card-title Jumpix
		/ 			p.card-text Custom Web Design & Development, Media, UX Design
		/ 			p View Project »
		/ 	.col-md-4
		/ 		= link_to portfolio_picnichour_path, class: 'portfolio-card card' do
		/ 		 	= image_tag "portfolio/portfolio-picnichour.jpg", :class=>"card-img", :alt=>"The Picnic Hour"
		/ 			.card-body
		/ 				h5.card-title The Picnic Hour
		/ 				p.card-text Shopify Website Design
		/ 				p View Project »
		/ .row.projects
		/ 	.col-md-4
		/ 		= link_to portfolio_cia_path, class: 'portfolio-card card' do
		/ 		  = image_tag "portfolio/portfolio-cia.jpg", :class=>"card-img", :alt=>"Construction Intern Awards"
		/ 		  .card-body
		/ 				h5.card-title Construction Intern Awards
		/ 				p.card-text Custom Wordpress Website
		/ 				p View Project »
		/ 	.col-md-4
		/ 		= link_to portfolio_reliantmass_path, class: 'portfolio-card card' do
		/ 		  = image_tag "portfolio/portfolio-reliantmass.jpg", :class=>"card-img", :alt=>"2021 Reliant Mass Campaign"
		/ 		  .card-body
		/ 				h5.card-title Reliant 2021 Mass Campaign
		/ 				p.card-text Custom Sales Landing Pages
		/ 				p View Project »
		.row.projects
			- random_projects(@project_title).each do |project|
				.col-md-4
					= link_to project[:path], class: 'portfolio-card card' do
						= image_tag project[:img], class: 'card-img', alt: project[:title]
						.card-body.d-flex.flex-column
							h5.card-title = project[:title]
							p.card-text.flex-grow-1 = project[:desc]
							p.text-lowercase View Project »

app/views/shared/_portfolio_cta.html.slim
section.get-started.cta
	.container
		.row.justify-content-center
			.col-lg-12
				h2.mx-auto Let’s create something great together.
				p.lead.text-center.mb-5 If you’re ready to transform your idea into an intuitive digital experience, I’m here to help.
		.row.mb-5
			.col-md-4
				i.fad.fa-phone
				h5 
					span 01.
				p 
					| Book a free 
					= link_to "15-minute consultation call ", "https://calendly.com/vanessa-amilet/15min?back=1"
					| & we’ll discuss your goals and create a custom proposal.
			.col-md-4
				i.fad.fa-comments
				h5
					span 02. 
				p Once you book, we’ll discuss the direction for your brand & website with plenty of opportunity for input & collaboration along the way.
			.col-md-4
				i.fad.fa-pencil-paintbrush
				h5 
					span 03. 
				p After a few weeks, you’ll receive your elevated website!
		.row
			.col-lg-12
				.text-center
					= link_to "Let's Work Together", contact_path, :class=>"btn btn-primary mr-3 center mb-5"
					p = link_to "Have any questions?", faqs_path, :class=>"cta"

app/views/shared/_portfolio_navigation.html.slim
- nav = project_navigation(@project_title)

section.portfolio-navigation
  .container
    .row.justify-content-between
      .col-6.text-start
        = link_to nav[:prev][:path], class: 'btn btn-secondary prev-project' do
          i.fad.fa-arrow-alt-circle-left
          = " #{nav[:prev][:title]}"
      .col-6.text-end
        = link_to nav[:next][:path], class: 'btn btn-secondary next-project' do
          = "#{nav[:next][:title]} "
          i.fad.fa-arrow-alt-circle-right

app/views/shared/_tools_strip.html.slim
/ app/views/shared/_tools_strip.html.slim
.tools-marquee.py-4
	.container
		p.text-center.mb-3
			| Tools that power my every day:

		.tools-marquee__wrap
			.tools-marquee__track aria-hidden="true"
				/ Duplicate the sequence twice so it loops seamlessly
				.tools-marquee__group
					h6.tool-item Figma
					span.separator *
					h6.tool-item Visual Studio Code
					span.separator *
					h6.tool-item Adobe Creative Cloud
					span.separator *
					h6.tool-item WordPress
					span.separator *
					h6.tool-item Slack
					span.separator *
					h6.tool-item ChatGPT
					span.separator *
					h6.tool-item GitHub
					span.separator *
					h6.tool-item Google Tag Manager
					span.separator *
					h6.tool-item Asana

				.tools-marquee__group
					h6.tool-item Figma
					span.separator *
					h6.tool-item Visual Studio Code
					span.separator *
					h6.tool-item Adobe Creative Cloud
					span.separator *
					h6.tool-item WordPress
					span.separator *
					h6.tool-item Slack
					span.separator *
					h6.tool-item ChatGPT
					span.separator *
					h6.tool-item GitHub
					span.separator *
					h6.tool-item Google Tag Manager
					span.separator *
					h6.tool-item Asana