config/routes.rb
Rails.application.routes.draw do

  get 'static/index'
  root 'static#index'

  get '/about'       => 'static#about'
  get '/portfolio'     => 'static#portfolio'
  get '/services'       => 'static#services'
  get '/privacy-policy'     => 'static#privacy-policy'
  get '/terms'     => 'static#terms'
  get '/faqs' => 'static#faqs'
  get '/links' => 'static#links'

  get '/portfolio/firmatek' => 'static#portfolio_firmatek'
  get '/portfolio/outwellness-atx' => 'static#portfolio_outwellnessatx'
  get '/portfolio/nonprofit-website' => 'static#portfolio_nonprofit_website', as: 'portfolio_foundation_website'
  get '/portfolio/community-impact-website' => 'static#portfolio_community_impact_website'
  get '/portfolio/youth-career-resource-website' => 'static#portfolio_youthcareer', as: 'portfolio_youthcareer'
  get '/portfolio/capitalize' => 'static#portfolio_capitalize'
  get '/portfolio/mfour' => 'static#portfolio_mfour'
  get '/portfolio/compost-products-website' => 'static#portfolio_greenerworld', as: 'portfolio_greenerworld'
  get '/portfolio/electrical-industry-website' => 'static#portfolio_electricalalliance', as: 'portfolio_electricalalliance'
  get '/portfolio/genie-creates' => 'static#portfolio_genie', as: 'portfolio_genie'
  get '/portfolio/north-bloom' => 'static#portfolio_northbloom', as: 'portfolio_northbloom'
  get '/portfolio/betty-boujee' => 'static#portfolio_bettyboujee', as: 'portfolio_bettyboujee'
  get '/portfolio/agency-website' => 'static#portfolio_agency', as: 'portfolio_agency'
  get '/portfolio/community-retail-showcase' => 'static#portfolio_community', as: 'portfolio_community'
  get '/portfolio/igco' => 'static#portfolio_igco'
  get '/portfolio/expertly-sanitized' => 'static#portfolio_expertlysanitized', as: 'portfolio_expertly'
  get '/portfolio/universal-control-systems' => 'static#portfolio_ucs', as: 'portfolio_ucs'
  get '/portfolio/marysol-wellness' => 'static#portfolio_marysol', as: 'portfolio_marysol'
  get '/portfolio/zack-pride' => 'static#portfolio_zackpride', as: 'portfolio_zackpride'
  get '/portfolio/leeward-team' => 'static#portfolio_leewardteam', as: 'portfolio_leewardteam'
  get '/portfolio/the-picnic-hour' => 'static#portfolio_picnichour', as: 'portfolio_picnichour'
  get '/portfolio/not-your-average-picnic' => 'static#portfolio_nyap', as: 'portfolio_nyap'
  get '/portfolio/picnics-in-the-city' => 'static#portfolio_picnics', as: 'portfolio_picnics'
  get '/portfolio/reliant-home-security' => 'static#portfolio_reliantsecurity', as: 'portfolio_reliantsecurity'
  get '/portfolio/reliant-mass-campaign' => 'static#portfolio_reliantmass', as: 'portfolio_reliantmass'
  get '/portfolio/joshespin' => 'static#portfolio_joshespin'
  get '/portfolio/jumpix' => 'static#portfolio_jumpix'
  get '/portfolio/ibuildamerica' => 'static#portfolio_iba', as: 'portfolio_iba'
  get '/portfolio/cia' => 'static#portfolio_cia'
  get '/portfolio/turner-mining-group' => 'static#portfolio_tmg', as: 'portfolio_tmg'
  get '/portfolio/captivecolour' => 'static#portfolio_captivecolour'
  get '/portfolio/snapple-video' => 'static#portfolio_snapple', as: 'portfolio_snapple'
  get '/portfolio/jarrod-lee' => 'static#portfolio_jarrodlee', as: 'portfolio_jarrodlee'

  get '/portfolio/apg' => 'static#portfolio_apg'
  get '/portfolio/hcss' => 'static#portfolio_hcss'
  get '/portfolio/artofgreenwood' => 'static#portfolio_greenwood'
  get '/portfolio/neydi-photography' => 'static#portfolio_neydiphotography', as: 'portfolio_neydi'
  get '/portfolio/manifesting-money-studio' => 'static#portfolio_mms', as: 'portfolio_mms'
  get '/portfolio/cameron-lee' => 'static#portfolio_csl', as: 'portfolio_csl'

  resources :contacts, only: :create
  match '/contact', to: 'contacts#new', via: 'get'

end

app/models/contact.rb
class Contact < MailForm::Base
	#include ActiveModel::Model
	attribute :name,      :validate => true
	attribute :business
	attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :phone_number
	attribute :website
	attribute :services
	attribute :budget
	attribute :message
	attribute :nickname,  :captcha  => true

	# Declare the e-mail headers. It accepts anything the mail method
	# in ActionMailer accepts.
	def headers
		{
			:subject => "Contact Vanessa Amilet - New Inquiry",
			:to => "vanessa.amilet@gmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@page_title = 'Contact'
		@page_description = 'Get in touch with Vanessa Amilet Creative to learn more about custom branding and website design services using the form on this page.'
		@page_keywords = 'Contact Vanessa Amilet Creative'
    	@contact = Contact.new
    end

    def create
      @contact = Contact.new(contact_params)
      @contact.request = request
      if @contact.deliver
      	name = params[:contact][:name]
      	email = params[:contact][:email]
      	#phone = params[:contact][:phone_number]
      	body = params[:contact][:message]
      	ContactMailer.contact_email(name, email, body).deliver
      	# flash.now[:error] = nil
       	# flash.now[:notice] = 'Thank you for your message. I will contact you soon!'
       	flash[:success] = "Thank you for your message. I will contact you soon!"
     	redirect_to contact_path
      else
      	#flash.now[:error] = 'There was an error sending your message. Please try again.'
      	#render :new
      	redirect_to contact_path, notice: "There was an error sending your message. Please try again."
      end
    end
    private
	    def contact_params
	    	params.require(:contact).permit(:name, :business, :email, :phone_number, :website, :services, :budget, :message, :nickname)
		end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/create.html.slim
/!  Contact Page
section.hero.d-flex
	.container
		.row.justify-content-center
			.col-md-10.col-lg-8
				.squiggle
				h1 Let's Work Together
				p.lead I'm excited to dive into the details of your project and discover how we can bring your ideas to life. Whether you're an established business refining your brand or a dynamic startup, I'm eager to initiate the conversation and embark on a collaborative journey with you.
/!  Begin Page Content 
section
	.container
		.row.contact-info
			.col-md-4
				.col-md.py-md-4.mb-5.mb-md-0
					i.fad.fa-clock
					h6 Business Hours
					p  Monday - Friday, 9:00am - 4:30pm EST 
				.col-md.py-md-4.mb-5.mb-md-0
					i.fad.fa-phone
					h6 Want to setup a time to talk? 
					p
						= link_to "Click here", "https://calendly.com/vanessa-amilet", target: "_blank"
						|  to schedule a consultation.
				.col-md.py-md-4
					i.fad.fa-question-circle
					h6 Need help?
					p 
						| Check out the 
						= link_to "FAQs", faqs_path 
						|  page to see if your question has been answered.
				.col-md.py-md-4.mb-5.mb-md-0
					i.fad.fa-envelope-open-text
					h6 Hate filling out forms?
					p
						| Email me:  
						= mail_to "vanessa.amilet@gmail.com", "vanessa.amilet@gmail.com"
						| .
			.offset-md-1.col-md-7
				- flash.each do |key, value| %
					- if value.is_a?(String)
					    	div.alert
					    		<a class="close" href="#" data-dismiss="alert">×</a>
					        	= content_tag :div, value, :id => "flash_#{key}"
				

app/views/contacts/new.html.slim
= content_for :body_class, 'contact'
/!  Contact Page
section.hero.d-flex
	.container
		.row.justify-content-center
			.col-md-10.col-lg-8
				.squiggle
				h1 Let's Work Together
				p.lead I'm excited to dive into the details of your project and discover how we can bring your ideas to life. Whether you're an established business refining your brand or a dynamic startup, I'm eager to initiate the conversation and embark on a collaborative journey with you.
/!  Begin Page Content 
section
	.container
		.row.contact-info
			.col-md-4
				.col-md.py-md-4.mb-5.mb-md-0
					i.fad.fa-clock
					h6 Business Hours
					p  Monday - Friday, 9:00am - 4:30pm EST 
				.col-md.py-md-4.mb-5.mb-md-0
					i.fad.fa-phone
					h6 Want to setup a time to talk? 
					p
						= link_to "Click here", "https://calendly.com/vanessa-amilet", target: "_blank"
						|  to schedule a consultation.
				.col-md.py-md-4
					i.fad.fa-question-circle
					h6 Need help?
					p 
						| Check out the 
						= link_to "FAQs", faqs_path 
						|  page to see if your question has been answered.
				.col-md.py-md-4.mb-5.mb-md-0
					i.fad.fa-envelope-open-text
					h6 Hate filling out forms?
					p
						| Email me:  
						= mail_to "vanessa.amilet@gmail.com", "vanessa.amilet@gmail.com"
						| .
			.offset-md-1.col-md-7
				/ #contact-form
				/ 	p Fill out the contact form below to get the conversation started. Please allow up to 2-3 business days to respond to your message.
					/ .form
					/ 	<iframe id="bonsai-form" onload="iframeLoaded()" src="https://app.hellobonsai.com/f/b372ec6c64fb9b8?embed=true&hide_header=true" frameborder="0" scrolling="no" width="100%" height="100%" style=""></iframe>
				#contact-form
					- flash.each do |key, value| %
						- if value.is_a?(String)
								= content_tag :div, :class=>"alert alert-#{key} fade show"
									<a class="close" href="#" data-dismiss="alert">×</a>
									= content_tag :div, value, :id => "flash_#{key}"

					p Fill out the contact form below to get the conversation started. Please allow up to 2-3 business days to respond to your message.
					
					= simple_form_for @contact, url: contacts_path, :html => {:class => 'form-horizontal needs-validation', :id => '' }, wrapper: :horizontal_form do |f|
						= f.error_notification

						= f.input :name do
							= f.input :name, :label => false ,:hint => true, :wrapper => false, :error => false, :class=>"validate", :required => true
						
						= f.input :business, :label => 'Business Name' do
							= f.input :business, :label => false ,:hint => true, :wrapper => false, :error => false, :class=>"validate", :required => false

						= f.input :email, :label => 'Email Address' do
							= f.input :email, :label => false, :hint => false, :wrapper => false, :error => true, :required => true, input_html: { autocomplete: 'email' }

						/= f.input :email, :wrapper => false, :error => true, :required => true, input_html: { autocomplete: 'email' }

						= f.input :phone_number, as: :tel, :label => 'Phone Number', :hint => false, :error => true, :type => "tel", :required => true
							/ span.bar

						= f.input :website, :label => 'Website (If Applicable)' do
							= f.input :website, :label => false, :hint => false, :wrapper => false, :error => true, :required => false

						= f.input :services, :label => 'What type of project are you inquiring about today?', as: :select, input_html: {class: 'form-select'}, collection: ["Basic Website Design","Custom Website Design", "Redesign of a Current Website","Sales Landing Page Design", "Graphic Design", "Website Maintenance", "1:1 Sessions ($175/hr)", "Other"], :required => true,  priority: [ "Website Design" ]

						/= f.input :budget, :label => 'What budget range do you have in mind for your project?', as: :select, input_html: {class: 'form-select'}, collection: ["$1,799+ USD (Landing Page Design)","$2,499+ USD (Basic Website Design)","$3,999+ USD (Custom Website Design)","$6k+ USD (Custom Website Design)", "$10k+ USD (Large-Scale Website Design)","Other"], :required => true
						

						= f.input :message, :label => 'Tell me about your project! What business problems are you hoping to solve?' do
							= f.input :message, :label => false , :as => :text, :input_html => {:rows => 6, :placeholder =>"" }, :wrapper => false,  :required => true

						.hidden
							= f.input :nickname, :hint => 'Leave this field blank!'
						.form-actions
							= f.button :submit, 'Send Message', :class=> "btn btn-primary contact-submit"